[torch][windows] Rebase aotriton patches, fix undeclared `mha_fwd_aot`. (#1227)
## Motivation

Windows nightly PyTorch builds are currently broken:
https://github.com/ROCm/TheRock/actions/workflows/release_windows_pytorch_wheels.yml?query=branch%3Amain.
This fixes them.

## Technical Details

Builds without `--enable-pytorch-flash-attention-windows` were failing
with `error: use of undeclared identifier 'mha_fwd_aot'`, but we also
needed to remove the `exclude(ATen_HIP_SRCS` code that was added
upstream to resolve `lld-link: error: undefined symbol ...
transform_bias_rescale_qkv_cuda`.

This is a minimal fix-forward for the first issue and restructures the
patches for the second issue.

Context:
* https://github.com/ROCm/TheRock/pull/1207#discussion_r2267878623
* https://github.com/pytorch/pytorch/pull/152951#discussion_r2267714825

## Test Plan

Built locally with `python build_prod_wheels.py build --pytorch-dir
D:/b/pytorch_main --pytorch-audio-dir D:/b/audio_main
--pytorch-vision-dir D:/b/vision_main --output-dir
%HOME%/.therock/pytorch --no-enable-pytorch-flash-attention-windows`

## Test Result

Local build succeeded.

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.