[windows] Fix fetch_package_targets without explicit AMDGPU_FAMILIES. (#834)
Progress on https://github.com/ROCm/TheRock/issues/542. The new Release
Windows packages job failed last night:
https://github.com/ROCm/TheRock/actions/runs/15633080737/job/44041709123

```
Run python ./build_tools/github_actions/fetch_package_targets.py
Traceback (most recent call last):
  File "/home/runner/work/TheRock/TheRock/./build_tools/github_actions/fetch_package_targets.py", line 47, in <module>
    main(args)
  File "/home/runner/work/TheRock/TheRock/./build_tools/github_actions/fetch_package_targets.py", line 35, in main
    family = info_for_key.get(package_platform).get("family")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

That failed because some AMDGPU families in
https://github.com/ROCm/TheRock/blob/main/build_tools/github_actions/amdgpu_family_matrix.py
only have information for "linux" and none for "windows". Fixed that
case and added unit tests. I had only tested manually with an explicit
family list, so I'm also removing the default "families" value to make
it easy to trigger with `workflow_dispatch` what would normally run on
`schedule`.