link correct version of hsa-runtime with c10_hip on pytorch 2.6.0 and 2.7.0 (#484)
Link to the version of hsa-runtime64 that is searched by LoadHIP.cmake
instead of relying to it to be linked as an amdhip64 dependency without
specifying the location.
(/usr/lib/x86_64-linux-gnu/libhsa-runtime64.so.1 in ubuntu 24.04)

This resolves following type of linking errors:
    TheRock/build/dist/rocm/lib/libamdhip64.so.6.5.25171-31afa624a:
    undefined reference tohsa_amd_vmem_map@ROCR_1'

fixes: https://github.com/ROCm/TheRock/issues/474

Signed-off-by: Mika Laitio <mika.laitio@amd.com>