[monorepo] Allow building hipCUB and rocThrust from the monorepo (#738)
Previously in the monorepo, running into an issue where `hipcub` was
searching for a `rocprim` component, however since the `rocprim` version
was ahead and `hipcub` was behind in our CMake, it was causing issues
from [this monorepo
run](https://github.com/ROCm/rocm-libraries/actions/runs/15304213808/job/43053064260)
such as:

```
hipCUB] /__w/rocm-libraries/rocm-libraries/math-libs/hipCUB/hipcub/include/hipcub/backend/rocprim/util_type.hpp:786:32: error: no template named 'radix_key_codec' in namespace 'rocprim'
[hipCUB]   786 |     using key_codec = rocprim::radix_key_codec<T>;
[hipCUB]       |                       ~~~~~~~~~^
```


This [TheRock CI monorepo
run](https://github.com/ROCm/rocm-libraries/actions/runs/15330308230/job/43135536362)
proves it is working! and this will point to the correct commit in
monorepo and work! (although s3 upload may not be working, but ignore
that since that's in another PR)