Revert "Add Python 3.13 to the workflow" (#818)
Reverts ROCm/TheRock#803

Our current manylinux dockerfile image
(https://github.com/ROCm/TheRock/blob/main/dockerfiles/cpubuilder/build_manylinux_x86_64.Dockerfile)
does not include Python 3.13:
https://github.com/ROCm/TheRock/actions/runs/15591037084/job/43909920339#step:5:15

> Run python_dir="/opt/python/cp313-cp313"
ERROR: Could not find python: /opt/python/cp313-cp313